# Generated by Django 6.0.2 on 2026-03-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
