# Generated by Django 6.0.2 on 2026-03-04 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursematerial_title'),
        ('users', '0002_alter_userprofile_photo_alter_userprofile_real_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_students', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_students', to='users.userprofile')),
            ],
        ),
    ]
